Repository teamSilabuz/projectunidad_frontend, pull requests merged in 2023-02, with the labels that each got.

#1 add estructura inicial carpetas: card,navbar,footer
  .gitignore
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.test.tsx
  src/App.tsx
  src/components/Cards/Card.css
  src/components/Cards/card.tsx
  src/components/Cards/index.tsx
  src/components/Footer/Footer.css
  src/components/Footer/index.tsx
  src/components/Navbar/Navbar.css
  src/components/Navbar/index.tsx
  src/components/index.tsx
  src/index.css
  src/index.tsx
  src/logo.svg
  src/pages/Gestor/Gestor.css
  src/pages/Gestor/index.tsx
  src/pages/index.tsx
  src/react-app-env.d.ts
  src/reportWebVitals.ts
  src/setupTests.ts
  tsconfig.json
Labels: feature

#2 feat: add login page and validations
  package.json
  src/App.tsx
  src/components/FormLogin/index.tsx
  src/components/index.tsx
  src/interfaces/user.ts
  src/pages/Login/index.tsx
  src/pages/index.tsx
  src/services/auth.ts
Labels: feature

#3 arreglado dimensiones de los items o cards
  package.json
  src/components/Cards/Card.css
  src/components/Cards/card.tsx
  src/components/Cards/index.tsx
  src/components/Footer/Footer.css
  src/components/Footer/index.tsx
  src/components/Navbar/index.tsx
  src/index.tsx
Labels: enhancement, feature

#4 feat: add register form
  src/App.tsx
  src/components/FormLogin/index.tsx
  src/components/FormRegister/index.tsx
  src/components/index.tsx
  src/pages/SingUp/index.tsx
  src/pages/index.tsx
  src/services/auth.ts
Labels: feature

#7 Feature/perfil usuario
  package.json
  src/App.css
  src/App.tsx
  src/components/Cards/Card.css
  src/components/Cards/card.tsx
  src/components/Cards/index.tsx
  src/components/Footer/index.tsx
  src/components/Navbar/Navbar.css
  src/components/Navbar/index.tsx
  src/components/ProfileUser/index.tsx
  src/components/index.tsx
  src/index.css
Labels: enhancement, feature

#8 add offcanvas for user and delete profileuser carpet
  src/components/Cards/index.tsx
  src/components/Navbar/Navbar.css
  src/components/Navbar/index.tsx
  src/components/ProfileUser/index.tsx
  src/components/index.tsx
Labels: enhancement, feature

#10 Feature/simulate-save-credential-external
  .gitignore
  src/App.tsx
  src/components/ExtCredential/index.tsx
  src/components/FormLogin/index.tsx
  src/components/FormRegister/index.tsx
  src/components/Navbar/index.tsx
  src/components/index.tsx
  src/interfaces/externCrerdential.ts
  src/pages/ExternalCredential/index.tsx
  src/pages/index.tsx
  src/services/extern-credential.ts
Labels: feature

#11 Feature/estilos modal rutaprotegida
  src/components/Cards/card.tsx
  src/images/password.jpg
  src/images/smscorreo.png
Labels: feature

#12 Feature/arreglar modal credencial
  package.json
  src/components/Cards/card.tsx
  src/services/auth.ts
Labels: bug, enhancement, feature

#13 Feat/consume boot api
  src/components/Cards/card.tsx
  src/components/Cards/index.tsx
  src/services/boot.ts
Labels: enhancement

#14 añadiendo cambios en navbar
  src/components/Cards/card.tsx
  src/components/Navbar/index.tsx
  src/services/auth.ts
Labels: enhancement, feature

#15 Feature/estilos
  package.json
  src/components/Cards/Card.css
  src/components/Cards/card.tsx
  src/components/Cards/index.tsx
  src/components/Footer/index.tsx
  src/components/Navbar/index.tsx
  src/interfaces/credenciales.tsx
Labels: enhancement, feature

#16 Feature/readme file
  README.md
  src/components/Cards/card.tsx
  src/components/Cards/index.tsx
  src/interfaces/credenciales.ts
  src/services/auth.ts
Labels: documentation

#17 feat: Se mejoró los estilos y responsive de las interfaces del aplica…
  public/index.html
  src/App.css
  src/components/Cards/Card.css
  src/components/Cards/card.tsx
  src/components/Cards/index.tsx
  src/components/ExtCredential/ExtCredencial.css
  src/components/ExtCredential/index.tsx
  src/components/Navbar/Navbar.css
  src/components/Navbar/index.tsx
  src/pages/Gestor/Gestor.css
Labels: enhancement

#18 integrate logout function to navbar
  src/components/Cards/Card.css
  src/components/Cards/card.tsx
  src/components/Cards/index.tsx
  src/components/ExtCredential/index.tsx
  src/components/Navbar/Navbar.css
  src/components/Navbar/index.tsx
  src/interfaces/credenciales.ts
Labels: enhancement

#19 add changes to get user profile
  src/components/Navbar/index.tsx
Labels: bug

#20 Release
  .env.example
  .gitignore
  .vercelignore
  README.md
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.test.tsx
  src/App.tsx
  src/components/Cards/Card.css
  src/components/Cards/card.tsx
  src/components/Cards/index.tsx
  src/components/ExtCredential/ExtCredencial.css
  src/components/ExtCredential/index.tsx
  src/components/Footer/Footer.css
  src/components/Footer/index.tsx
  src/components/FormLogin/index.tsx
  src/components/FormRegister/index.tsx
  src/components/Navbar/Navbar.css
  src/components/Navbar/index.tsx
  src/components/index.tsx
  src/images/candado1.jpg
  src/images/credencial.png
  src/images/password.jpg
  src/images/smscorreo.png
  src/index.css
  src/index.tsx
  src/interfaces/credenciales.ts
  src/interfaces/externCrerdential.ts
  src/interfaces/user.ts
  src/logo.svg
  src/pages/ExternalCredential/index.tsx
  src/pages/Gestor/Gestor.css
  src/pages/Gestor/index.tsx
  src/pages/Login/index.tsx
  src/pages/SingUp/index.tsx
  src/pages/index.tsx
  src/react-app-env.d.ts
  src/reportWebVitals.ts
  src/router/ProtectedRoute.tsx
  src/router/PublicRoute.tsx
  src/services/auth.ts
  src/services/boot.ts
  src/services/extern-credential.ts
  src/setupTests.ts
  tsconfig.json
Labels: documentation, enhancement
